//! LuaLS type stubs for the whole SDK, assembled from the annotation block
//! each module keeps beside its bindings. `ermod-dev stubs` writes this out
//! so authors get completion and type checking in any editor with the Lua
//! language server; the manifest and entry-point shapes are described here
//! because no single module owns them.

const std = @import("std");
const log = @import("log.zig");
const hooks = @import("hooks.zig");
const params = @import("params.zig");
const perf = @import("perf.zig");
const store = @import("store.zig");
const ui = @import("ui.zig");
const screen = @import("screen.zig");

const header =
    \\---@meta ermod
    \\-- Type stubs for the ermod Lua SDK. Generated by `ermod-dev stubs`; do not edit.
    \\-- Point your Lua language server at the directory holding this file
    \\-- (e.g. .luarc.json: { "workspace.library": ["path/to/stubs"] }).
    \\
    \\---@alias ermod.run_at "launch"|"events"
    \\---@alias ermod.permission "log"|"hooks"|"params"|"perf"|"store"|"ui"|"screen"
    \\
    \\---The `sdk` table a mod's entry point receives. Only the modules the
    \\---manifest's `permissions` list are present; the rest are nil.
    \\---@class ermod.sdk
    \\---@field log ermod.sdk.log?
    \\---@field hooks ermod.sdk.hooks?
    \\---@field params ermod.sdk.params?
    \\---@field perf ermod.sdk.perf?
    \\---@field store ermod.sdk.store?
    \\---@field ui ermod.sdk.ui?
    \\---@field screen ermod.sdk.screen?
    \\
    \\---The table a mod script returns.
    \\---@class ermod.mod
    \\---@field name string
    \\---@field version string
    \\---@field run_at ermod.run_at
    \\---@field permissions ermod.permission[]
    \\---@field on_launch fun(sdk: ermod.sdk)? # run_at = "launch": runs once at load (and on hot-reload)
    \\---@field setup fun(sdk: ermod.sdk)?     # run_at = "events": registers handlers with sdk.hooks
    \\
    \\
;

/// The complete stub file.
pub const text = header ++
    log.stub ++ "\n" ++
    hooks.stub ++ "\n" ++
    params.stub ++ "\n" ++
    perf.stub ++ "\n" ++
    store.stub ++ "\n" ++
    ui.stub ++ "\n" ++
    screen.stub;

const testing = std.testing;

test "every bound SDK function has a stub" {
    // The names each module's `push` sets on its table; a new binding must
    // be added here and in the module's stub block.
    const bound = [_][]const u8{
        "log.info",      "log.warn",       "log.error",
        "hooks.on",      "params.row",     "params.rows",
        "perf.frame_ms", "perf.fps",       "perf.frame",
        "perf.now_ms",   "perf.mods",      "store.get",
        "store.set",     "store.keys",     "ui.window",
        "ui.text",       "ui.button",      "ui.checkbox",
        "ui.slider",     "ui.slider_int",  "ui.input",
        "ui.combo",      "ui.plot",        "ui.progress",
        "ui.separator",  "ui.same_line",   "ui.spacing",
        "ui.focused",    "screen.capture",
    };
    for (bound) |name| {
        var buf: [64]u8 = undefined;
        const needle = try std.fmt.bufPrint(&buf, "function {s}(", .{name});
        if (std.mem.indexOf(u8, text, needle) == null) {
            std.debug.print("missing stub for {s}\n", .{name});
            return error.MissingStub;
        }
    }
}

test "the stub file starts with the meta marker and describes the manifest" {
    try testing.expect(std.mem.startsWith(u8, text, "---@meta ermod"));
    try testing.expect(std.mem.indexOf(u8, text, "@class ermod.mod") != null);
    try testing.expect(std.mem.indexOf(u8, text, "@class ermod.sdk\n") != null);
}
