---@meta ermod
-- Type stubs for the ermod Lua SDK. Generated by `ermod stubs`; do not edit.
-- Point your Lua language server at the directory holding this file
-- (e.g. .luarc.json: { "workspace.library": ["path/to/stubs"] }).

---@alias ermod.run_at "launch"|"events"
---@alias ermod.permission "log"|"hooks"|"params"|"perf"|"store"|"ui"|"screen"

---The `sdk` table a mod's entry point receives. Only the modules the
---manifest's `permissions` list are present; the rest are nil.
---@class ermod.sdk
---@field log ermod.sdk.log?
---@field hooks ermod.sdk.hooks?
---@field params ermod.sdk.params?
---@field perf ermod.sdk.perf?
---@field store ermod.sdk.store?
---@field ui ermod.sdk.ui?
---@field screen ermod.sdk.screen?

---The table a mod script returns.
---@class ermod.mod
---@field name string
---@field version string
---@field run_at ermod.run_at
---@field permissions ermod.permission[]
---@field on_launch fun(sdk: ermod.sdk)? # run_at = "launch": runs once at load (and on hot-reload)
---@field setup fun(sdk: ermod.sdk)?     # run_at = "events": registers handlers with sdk.hooks

---@class ermod.sdk.log
local log = {}

---Write an info line to the engine log, tagged with this mod's name.
---@param msg string
function log.info(msg) end

---Write a warning line.
---@param msg string
function log.warn(msg) end

---Write an error line.
---@param msg string
function log.error(msg) end

---@alias ermod.event
---| "on_present"    # a frame is about to be presented; handlers must be cheap. Payload: {}
---| "on_rune_gain"  # the player gained runes. Payload: { amount = integer }
---| "on_death"      # the player died. Payload: {}

---@class ermod.event.payload
---@field amount integer? # on_rune_gain only

---@class ermod.sdk.hooks
local hooks = {}

---Subscribe to a named engine event. Unknown names are an error at
---subscribe time. Handlers run under the instruction budget; a handler
---that errors strikes the mod (three strikes disables it), one that
---exhausts its budget disables it on the spot.
---@param event ermod.event
---@param handler fun(ev: ermod.event.payload)
function hooks.on(event, handler) end

---A live param row. Fields are the paramdef's field names, read and
---written by name; `id` is the row id unless the paramdef has such a
---field. Writes land in game memory at once and last for the process.
---@class ermod.params.row
---@field id integer
---@field [string] number

---@class ermod.sdk.params
local params = {}

---One row of a param file by id, or nil if there is no such row.
---Errors if the file is unknown, not loaded yet, or the live table
---does not match the vendored paramdef.
---@param file string # e.g. "CharaInitParam" (".param" optional)
---@param id integer
---@return ermod.params.row?
function params.row(file, id) end

---Iterate every row of a param file in table order.
---@param file string
---@return fun(): ermod.params.row?
function params.rows(file) end

---@class ermod.perf.mod
---@field name string
---@field last_ms number  # cost of the mod's most recent handler call
---@field avg_ms number   # mean over the last 120 calls
---@field total_ms number # since load
---@field calls integer

---@class ermod.sdk.perf
local perf = {}

---Last present-to-present interval in milliseconds.
---@return number
function perf.frame_ms() end

---Moving-average frames per second over the last 120 frames.
---@return number
function perf.fps() end

---Frames presented since the hook went live.
---@return integer
function perf.frame() end

---Monotonic clock in milliseconds, for a mod's own timing.
---@return number
function perf.now_ms() end

---Per-mod handler cost for every loaded mod (not only the caller).
---@return ermod.perf.mod[]
function perf.mods() end

---@alias ermod.store.value string|number|boolean

---@class ermod.sdk.store
local store = {}

---A stored value, or `default` when unset. Keys match [A-Za-z0-9_.-]+.
---@generic T : ermod.store.value
---@param key string
---@param default T?
---@return T
function store.get(key, default) end

---Persist a value (the whole store is written at once). nil deletes.
---@param key string
---@param value ermod.store.value|nil
function store.set(key, value) end

---Every stored key, sorted.
---@return string[]
function store.keys() end

---@alias ermod.ui.color number[] # {r, g, b [, a]} in 0..1
---@alias ermod.ui.flag "no_title"|"no_resize"|"no_move"|"no_background"|"auto_size"|"no_inputs"

---@class ermod.ui.window_opts
---@field x number?
---@field y number?
---@field w number?
---@field h number?
---@field once boolean? # apply position/size only the first time (default true)
---@field flags ermod.ui.flag[]?

---@class ermod.ui.plot_opts
---@field min number?
---@field max number?
---@field height number?
---@field overlay string?

---Immediate-mode overlay widgets. Every call is only legal inside a
---frame — from a handler running during on_present (or the state
---events derived there); elsewhere it is an error. Widgets that edit a
---value take the current value and return the new one. Labels are
---unique per window; use "Label##id" to disambiguate.
---@class ermod.sdk.ui
local ui = {}

---Draw a window; `body` runs between Begin/End and can never leave one open.
---@param title string
---@param body fun()
---@param opts ermod.ui.window_opts?
function ui.window(title, body, opts) end

---@param s string
---@param color ermod.ui.color?
function ui.text(s, color) end

---@param label string
---@return boolean pressed
function ui.button(label) end

---@param label string
---@param value boolean
---@return boolean
function ui.checkbox(label, value) end

---@param label string
---@param value number
---@param min number
---@param max number
---@return number
function ui.slider(label, value, min, max) end

---@param label string
---@param value integer
---@param min integer
---@param max integer
---@return integer
function ui.slider_int(label, value, min, max) end

---Single-line text input (up to 255 bytes).
---@param label string
---@param value string
---@return string
function ui.input(label, value) end

---Drop-down; `index` is 1-based into `items`.
---@param label string
---@param index integer
---@param items string[]
---@return integer
function ui.combo(label, index, items) end

---Line plot of up to 1024 samples.
---@param label string
---@param samples number[]
---@param opts ermod.ui.plot_opts?
function ui.plot(label, samples, opts) end

---@param fraction number # 0..1
---@param overlay string?
function ui.progress(fraction, overlay) end

function ui.separator() end
function ui.same_line() end
function ui.spacing() end

---Whether the overlay currently has input focus (Insert toggles it).
---@return boolean
function ui.focused() end

---@class ermod.sdk.screen
local screen = {}

---Capture the next presented frame to `C:\ermod\captures\<name>.png`
---(the overlay included). `name` defaults to `<mod>-<n>`; it may only
---contain letters, digits, `.`, `_`, `-`. `scale` (1..16, default 1)
---box-downsamples the image by that factor. Returns the path the file
---will be written to, or nil and a reason (no capture on this host, or
---one is already pending).
---@param name string?
---@param scale integer?
---@return string? path
---@return string? reason
function screen.capture(name, scale) end
