#!/usr/bin/env python3
"""Generate Zig field tables from Paramdex PARAMDEF XML files.

Usage: gen_paramdef.py <paramdefs_dir> <out.zig> <ParamName> [ParamName ...]

Field offsets are computed by walking the <Fields> list in order, mirroring how
FromSoftware packs rows: fields are laid out contiguously with no alignment
padding (padding is explicit via `dummy8` fields), and consecutive bitfields
share a storage unit until it is full.

Note on bitfields: `dummy8` is a padding type but packs into the *same* storage
unit as an adjacent `u8` bitfield, so bit packing keys on the storage size, not
on the type name. In CharaInitParam this is what makes the row 320 bytes rather
than 321.
"""

import re
import sys
import xml.etree.ElementTree as ET

SIZES = {
    "u8": 1, "s8": 1, "dummy8": 1,
    "u16": 2, "s16": 2,
    "u32": 4, "s32": 4, "f32": 4,
    "u64": 8, "s64": 8, "f64": 8,
}

DEF_RE = re.compile(
    r"^(?P<type>\w+)\s+(?P<name>\w+)"
    r"(?:\[(?P<array>\d+)\])?"
    r"(?:\s*:\s*(?P<bits>\d+))?"
    r"(?:\s*=\s*(?P<default>.*))?$"
)


def parse_fields(path):
    root = ET.parse(path).getroot()
    param_type = root.find("ParamType").text.strip()

    offset = 0
    bit_offset = 0
    bit_unit_size = 0
    bit_unit_start = 0
    fields = []

    for field in root.find("Fields"):
        raw = field.get("Def").strip()
        m = DEF_RE.match(raw)
        if not m:
            raise SystemExit(f"unparsed field def: {raw!r}")

        typ = m.group("type")
        name = m.group("name")
        array = m.group("array")
        bits = m.group("bits")
        size = SIZES[typ]

        if bits:
            bits = int(bits)
            # Continue the current storage unit if the new bitfield still fits;
            # key on unit size, not type name, so dummy8 packs with u8.
            if bit_unit_size != size or bit_offset + bits > size * 8:
                bit_unit_size = size
                bit_offset = 0
                bit_unit_start = offset
                offset += size
            fields.append({
                "name": name, "type": typ, "offset": bit_unit_start,
                "count": 1, "bit_offset": bit_offset, "bit_width": bits,
            })
            bit_offset += bits
            continue

        bit_unit_size = 0
        bit_offset = 0
        count = int(array) if array else 1
        fields.append({
            "name": name, "type": typ, "offset": offset,
            "count": count, "bit_offset": None, "bit_width": None,
        })
        offset += size * count

    return param_type, offset, fields


def zig_ident(name):
    return name if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name) else f'@"{name}"'


def emit(out, defs):
    out.write("//! Generated by tools/gen_paramdef.py from Paramdex PARAMDEF XML.\n")
    out.write("//! Do not edit by hand; re-run the generator instead.\n\n")
    out.write('const std = @import("std");\n')
    out.write('const paramdef = @import("../paramdef.zig");\n')
    out.write("const Field = paramdef.Field;\n\n")

    for param_name, (param_type, row_size, fields) in defs.items():
        out.write(f"pub const {zig_ident(param_name)} = struct {{\n")
        out.write(f'    pub const param_type = "{param_type}";\n')
        out.write(f"    pub const row_size = {row_size};\n\n")
        out.write("    pub const fields = [_]Field{\n")
        for f in fields:
            if f["type"] == "dummy8" and f["bit_width"] is None:
                continue  # explicit padding: no reason to expose it
            bit_off = "null" if f["bit_offset"] is None else str(f["bit_offset"])
            bit_w = "null" if f["bit_width"] is None else str(f["bit_width"])
            out.write(
                f'        .{{ .name = "{f["name"]}", .kind = .{f["type"]}, '
                f'.offset = {f["offset"]}, .count = {f["count"]}, '
                f".bit_offset = {bit_off}, .bit_width = {bit_w} }},\n"
            )
        out.write("    };\n")
        out.write("};\n\n")


def main():
    if len(sys.argv) < 4:
        raise SystemExit(__doc__)
    src_dir, out_path, names = sys.argv[1], sys.argv[2], sys.argv[3:]

    defs = {}
    for name in names:
        defs[name] = parse_fields(f"{src_dir}/{name}.xml")
        print(f"{name}: {defs[name][0]}, row_size={defs[name][1]}, "
              f"{len(defs[name][2])} fields")

    with open(out_path, "w") as out:
        emit(out, defs)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
